### ISSUE TITLE
Dejo de funcionar

### ISSUE THREAD

**Issue by ggroel** [sbehrends/homebridge-bgh-smart#13]
Hola, cómo estás... de un momento a otro (quizás por alguna actualización de algún componente) dejó de funcionar el plugin... o sea, el homebridge los encuentra, los agrega a la aplicación casa, pero no se puede controla desde allí. Con la aplicación de BGH si se puede, pero desde CASA no. Tengo otros dispositivos y siguen funcionando normalmente, solo los aires dejaron de funcionar. No hay errores en el log de homebridge. Podrás ayudarme?. GRACIAS!!!

**Comment by sbehrends** [comment]
Como conversamos por Twitter, el plugin esta funcionando correctamente.
